// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAGx5dt-1Rs5irfcMOHatsczGcIwK_lqY',
    appId: '1:484853537775:web:fe6c4859f652a3569e741a',
    messagingSenderId: '484853537775',
    projectId: 'ciphernest-d188b',
    authDomain: 'ciphernest-d188b.firebaseapp.com',
    storageBucket: 'ciphernest-d188b.firebasestorage.app',
    measurementId: 'G-KECKNG0MN3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAGx5dt-1Rs5irfcMOHatsczGcIwK_lqY',
    appId: '1:484853537775:web:e381b850a0ab3a8b9e741a',
    messagingSenderId: '484853537775',
    projectId: 'ciphernest-d188b',
    authDomain: 'ciphernest-d188b.firebaseapp.com',
    storageBucket: 'ciphernest-d188b.firebasestorage.app',
    measurementId: 'G-DKKM8QB9R3',
  );
}
